name: Release

on:
  push:
    branches: [ release/* ]

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10']
        os: [windows-latest] # or [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.github_token }}

        # If the commit is tagged with a version (e.g. "v0.3.4"),
        # release the app after building
        release: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.') }}
